# Generated by Django 4.1.4 on 2023-05-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
