# Generated by Django 4.1.5 on 2023-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
