# Generated by Django 4.1.5 on 2023-06-07 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_delete_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fllwer', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
