# Generated by Django 4.1.5 on 2023-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.ManyToManyField(related_name='likedPosts', to='network.post'),
        ),
    ]
